# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 18:50
from __future__ import unicode_literals

from django.db import migrations
import hemres.siterelated


class Migration(migrations.Migration):

    dependencies = [
        ('hemres', '0005_add_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newsletter',
            managers=[
                ('objects', hemres.siterelated.CurrentSiteManager()),
            ],
        ),
    ]
